version: '2'

services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
            MYSQL_DATABASE: 'default'

    php72:
        build: docker/php72/
        image: talisorm/php72:latest
        volumes:
            - ./:/app:cached
            - ~/.composer:/tmp
        environment:
            COMPOSER_HOME: /tmp
            BLACKFIRE_CLIENT_ID: ${BLACKFIRE_CLIENT_ID}
            BLACKFIRE_CLIENT_TOKEN: ${BLACKFIRE_CLIENT_TOKEN}

    phpstan:
        build: docker/phpstan/
        image: talisorm/phpstan
        volumes:
            - ./:/app:cached
